### PR TITLE
Correct levelized_cost calculation

### PR DESCRIPTION
**Pull request by OFR-IIASA**
As explained in issue #652, this PR aims to adjust the calculation of levelized_costs, so that these are not only calculated when investment costs are parametrized for a technology, but also when variable costs *only* have been defined.

## How to review

- Read the diff and note that the CI checks all pass.
A Specific test cannot be written because it is not possible to retrieve the parameter "levelized_cost" from the scenario object.

## PR checklist

- [x] Continuous integration checks all ✅
~- [ ] Add or expand tests; coverage checks both ✅~
- [x] Add, expand, or update documentation.
- [x] Update release notes.

### CODE REVIEW

**Comment by OFR-IIASA** [comment]
@behnam-zakeri as discussed yesterday, let us extend the calculation of the levelized costs to include the relation-related costs as well. Also, the issues raised on @khaeru can also be addressed in this PR:
- This PR resulted in a line (the one for https://github.com/iiasa/message_ix/pull/645) appearing twice in the release notes.
- Some of the edits to doc/macro.rst result in a sentence appearing in all bold [here](https://docs.messageix.org/en/latest/macro.html#general-configuration-sheet).

**Comment by gidden** [comment]
This seems like a key update that should be tested if at all possible. I wonder if it's possible to use the existing dantzig problem to test levelized cost values with
- `inv_cost` only
- `fix_cost` only
- both `inv_cost` and `fix_cost`

**Comment by OFR-IIASA** [comment]
@gidden I agree, and also to test the 'var_cost' as well as the additions to the formulation related to relations. I believe by solving using the command solve(var_list=["levelized_cost"]) we will hopefully be able to retrieve the levelized_cost from the scenario object.

**Comment by OFR-IIASA** [comment]
In order to address the issues associated with creating tests for this PR, an issue has been started, see #661

**Review by behnam-zakeri — CHANGES_REQUESTED** [review]
Thanks @OFR-IIASA . Can you please merge my edits/corrections suggested through #658 so that we see all proposed changes together here?

**Comment by OFR-IIASA** [comment]
@behnam-zakeri , my proposal would be to merge this PR first and then change the PR for #658 to main. The reason is that while here we are only just changing "when" the `levelized_cost` are being calculated, the changes in #658 change how these are calculated. I would therefore propose to add tests for the other PR, but for some changes on the java end are required to allow doing this. I therefore propose to merge this PR as is and continue work on #658 thereafter.

**Review by behnam-zakeri — APPROVED** [review]

**Review by gidden — APPROVED** [review]
LGTM, thanks @OFR-IIASA ! I will update to latest main and merge.

**Comment by gidden** [comment]
The failed test here is from a test timeout, e.g., 

```
FAILED message_ix/tests/test_tutorials.py::test_tutorial[westeros_addon_technologies] - nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 10 seconds.
```

Will merge now.

**Comment by gidden** [comment]
Noting previous tests passed except the noted failures, merging.

**Pull request merged**
