### PR TITLE
Update Westeros tutorial: firm capacity

### PR DESCRIPTION
**Pull request by OFR-IIASA**
This PR updates the tutorial on adding firm capacity.

This is the first of three tutorials on various features surrounding the renewables"

## How to review

Run tutorial
Read through tutorials and see if the explanantions are understandable 

## PR checklist

~ - [ ] Tests added. Tutorial added~
~ - [ ] Documentation added. already included ~
- [x] Release notes updated.

### CODE REVIEW

**Comment by khaeru** [comment]
Postpone to v3.3, as indicated by @OFR-IIASA on 2021-01-13.

**Review by behnam-zakeri — COMMENTED** [review]
Thanks @OFR-IIASA for this useful tutorial. In general, it is clear and the user should be able to follow.
Some suggestions:
- the example of US power system is good. Maybe one or two sentences would help that why we use this number also for this tutorial. I added some text in the PR.
- I see you have reverted the units t "???". Is there any specific reason? Otherwise, a unit like "-" can be easier.
- It would be very nice if we could see a visual of this concept. It can be two, three bars next to each other showing average load, peak load, wind and capacity, and share of wind and coal capacity that is considered firm.

**Review by behnam-zakeri — COMMENTED** [review]
Thanks @OFR-IIASA for the improvements. I confirm the PR is ready to merge from the content viewpoint.

**Review by khaeru — APPROVED** [review]
Rebased to deconflict RELEASE_NOTES; also reworded the commit messages per the style guide.

Approved, assuming CI checks will pass. LGTM!

**Pull request merged**
