### PR TITLE
WIP (do not merge) - add a FAQ page and update the docs to remove `ixmp` as submodule

### PR DESCRIPTION
**Pull request by danielhuppmann**
This PR adds an FAQ and cleans up the documentation pages to reflect that `ixmp` is not included as a submodule any more.

### CODE REVIEW

**Comment by gidden** [comment]
lgtm, still a WIP?

**Comment by gidden** [comment]
Ok, also see your email now..

**Comment by danielhuppmann** [comment]
please review whenever you have a minute, @gidden

**Comment by gidden** [comment]
lgtm!

**Pull request merged**
