### PR TITLE
Update scenarios.yaml

### LINKED ISSUE #428: Adjust expected outcome for nightly tests
#421 was merged without adjusting `message_ix/tests/data/scenarios.yaml`, which gives the expected objective function values for the nightly tests of "full-size" (MESSAGEix-GLOBIOM) scenarios:
https://github.com/iiasa/message_ix/blob/7ee162891b2e9ae6fdbed58e63727955689961e6/message_ix/tests/data/scenarios.yaml#L1-L23

As a result, these tests now fail every time. See e.g. https://github.com/iiasa/message_ix/runs/1490655883?check_suite_focus=true#step:9:44

@MiguelPobleteCazenave @volker-krey can you please identify who will address this, and assign this issue to them?

### PR DESCRIPTION
**Pull request by MiguelPobleteCazenave**
Update values for the nightly tests, left over from #421. Closes #428.

Also adjustments similar to iiasa/ixmp#389:
- Replace xlrd with openpyxl for pandas I/O from/to Excel files.
- Add setting required by sphinxcontrib-bibtex ≥ 2.0.0.

## How to review

Run the nightly tests and confirm that the expected values match the observed ones.

## PR checklist

- ~Add or expand tests.~ N/A, only updating
- ~Add, expand, or update documentation.~
- ~Update release notes.~

### CODE REVIEW

**Comment by MiguelPobleteCazenave** [comment]
btw, all the test are failing in the pull request due to some issues with the xlrd package

**Comment by khaeru** [comment]
Thanks @MiguelPobleteCazenave. I will:

- Add more text to docs/source/contributing.rst that describing when and how to run these checks / update this file.
- Push a temporary commit to force these tests to run just once, to ensure the updated values work on GitHub Actions, then force-push the branch to remove it.

Meanwhile, could you please complete the PR description?

- Remove the texts starting “**Required:**.”—these are only templates/prompts to the PR author (you).
- For the checklist, per the comments, you can use strike-through like this:
  - ~Add or expand tests.~ N/A, only updating

**Comment by khaeru** [comment]
> btw, all the tests are failing in the pull request (and everywhere else) due to some issues with the xlrd package

This was iiasa/ixmp#388, fixed by iiasa/ixmp#389.

**Comment by khaeru** [comment]
So the commit labelled “Temporarily force 'nightly' CI jobs to check previous commit” changed .github/workflows/nightly.yaml from:
```yaml
on:
  # Uncomment these two lines for debugging, but leave them commented on the
  # master branch
  # pull_request:
  #   branches: [ master ]
```
to:
```yaml
on:
  # Uncomment these two lines for debugging, but leave them commented on the
  # master branch
  pull_request:
    branches: [ master ]
```

This caused [this job](https://github.com/iiasa/message_ix/runs/1551486012) to run immediately. Both of the 2 tests pass, confirming that the change to scenarios.yaml will work when the job runs nightly.

Next I'll edit the branch to remove this commit, and force-push. The link above to the successful job will continue to work, even though the commit will disappear from the branch. Another option would be to add a second commit re-commenting those lines, but the first way keeps a cleaner commit history.

**Review by khaeru — APPROVED** [review]

**Pull request merged**
