### PR TITLE
update R tutorial and include testing

### PR DESCRIPTION
**Pull request by adrivinca**
I updated the name and some parts of the Austrian R tutorials and updated the documentation with new links. I also added some code that run the R tutorial while testing if the flag option `--test-r` is used.

## How to review

- Build the documentation and check the installation part and the tutorial page related to R
- run the tests including the R tutorials, as described in the documentation `py.test --test-r`

### CODE REVIEW

**Comment by adrivinca** [comment]
Thanks to @guofei2016 I also found that running the tutorials' code on Rstudio fails at solving. It seems a path issue and after some debugging the path seems indeed correct.
Strangely, running on Jupyter or from command line with `Rscript` works

I attached an example, the austrian tutorial written in R.
@guofei2016 or @volker-krey could you please try, after making sure the austrian tutorial works for you, try to run file I send you in Rstudio and then form command line? `Rscript austrian.R`

To check whether these conclusions are correct. Then it would be something with Rstudio that I can not figure out. Thanks!

**Comment by volker-krey** [comment]
@adrivinca related to issues with running message_ix in RStudio, I noticed different setting of the PATH environment variable in Jupyter notebooks (where code works fine) compared to RStudio. The difference that I noticed is that in the Jupyter environment the user-specific part of the PATH environment variable which typically contains the Anaconda related paths, is added before the system part of the PATH variable. If I modify the PATH variable in RStudio manually in this way, then the code also works in RStudio. I have not figured out how to access the user- and system-specific parts of the PATH variable, so just did a quick and dirty manual addition which solves the issue, but is unfortunately not transferable.

**Comment by khaeru** [comment]
@adrivinca @volker-krey something I'm not clear on: have you installed Anaconda and RStudio *in parallel*, or installed the latter *via* the former (e.g. as outlined [here](https://docs.anaconda.com/anaconda/user-guide/tasks/using-r-language/) and [here](https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment/))?

There are many ways for a user to set up their system. Our install docs could recommend one, and/or qualify installation advice ("ensure your RStudio installation has the correct environment set up…") so it's specific to the case in which it applies, and/or mention that some combinations are not tested/supported.

Also found this while searching "RStudio anaconda paths": https://community.rstudio.com/t/how-to-add-conda-to-path-in-rstudio-with-new-conda-initialization/12182

**Comment by adrivinca** [comment]
@khaeru I think we both have anaconda and Rstudio installed separately. It is quite unlikely that any R user will have it installed through anaconda, that's why so far the parallel systems is the only case we look at.

@volker-krey I tried the path change you suggested but I still have the same solving issues

**Comment by khaeru** [comment]
Postponing to after v3.0.

**Comment by khaeru** [comment]
To rebase, resolve the conflicts, carry over R CI improvements from ixmp, and address #251, I opened #377 which supersedes this PR. Thanks @adrivinca for getting this started!

**Pull request closed without merging**
