### PR TITLE
new formulation of the capacity maintenance 

### PR DESCRIPTION
**Pull request by ClaraLuisa**
The capacity maintenance was seperated into three seperate equations to ensure that capacity that is built during one periode also exists as cap by the end of the periode.

### CODE REVIEW

**Comment by ClaraLuisa** [comment]
This PR changes the capacity maintenance equation to omit technologies that have a CAP_NEW not showing up in CAP by the end of the periode.

**Comment by danielhuppmann** [comment]
thanks @ClaraLuisa, nice work! but for easier testing and review, can you please make a new branch from the latest master and cherry-pick this commit, and then make a PR directly into the master branch? After all, this change does not depend on any of the hackathon developments...

It seems that CircleCI fails because of an infeasibility, and as the PR now mixes the all-modes extension and your new-capacity formulation, it is difficult to tell why that happens...

**Comment by ClaraLuisa** [comment]
sure, no problem!

**Comment by ClaraLuisa** [comment]
closed in favour of #88

**Pull request closed without merging**
