### PR TITLE
Ensure MESSAGE.enforce() runs for MESSAGE_MACRO

### LINKED ISSUE #591: Address failing nightly workflow
As first mentioned by @khaeru in the #message_general slack channel, the nightly workflow is failing possible after merging #561, please see [here](https://github.com/iiasa/message_ix/runs/6188543164?check_suite_focus=true#step:9:20).
Please find further information under the thread in #message_general [here](https://iiasa-ece.slack.com/archives/CD0GBHHA4/p1651055949497499).

Taking the liberty to copy @behnam-zakeri tip to check weather the failing nightly is related to the merged PR:

> Before this PR, if there was `capacity_factor` of zero in the input data, the formulation would convert it to 1, because GAMS couldn't understand if this is a zero or a missing value. Our GAMS formulation makes missing `capacity_factor` values equal to 1, and still does that. But after this PR, zero values are not considered missing values, and should remain zero. What we can check is that if there is any input `capacity_factor` equal to zero in this scenario or not. This can be checked like:
>```
>df = sc.par("capacity_factor")
>assert df.loc[df["value"] == 0].empty
>```

### PR DESCRIPTION
**Pull request by khaeru**
Closes #591 by ensuring that the MESSAGE.enforce() method, ensuring consistency of internal sets and parameters, is called when a scenario is solved using the MESSAGE_MACRO class.

Note that this demonstrates the workflow described at https://github.com/iiasa/message_ix/pull/603#issuecomment-1123486549:
> 1. Author opens a PR with some commits. Status in our tracker is "In progress".
> 2. Identifying that their PR ~touches the GAMS implementation~ involves the nightly tests, author pushes a commit uncommenting these lines: https://github.com/iiasa/message_ix/blob/b572ccee45c293a88f1f2acf91a0811d50cf6593/.github/workflows/nightly.yaml#L6-L8 with a message like `TEMPORARY Enable nightly workflow for PR.`
> 3. Author develops their PR, pushing commits, noting and ensuring that the "pytest", "lint" **and** "nightly" checks pass.
> 4. Author requests a review; status is "In review".
> 5. Reviewer does the review, possibly requesting changes.
> 6. Review and author interact until reviewer is satisfied.
> 7. Reviewer approves.
> 8. Author or maintainer performs `git rebase -i` on the branch to `drop` the "TEMPORARY" commit from step 2.
> 9. Merge.

## How to review

- Read the diff and note that the CI checks all pass.
- Run specific scenarios as described at https://github.com/iiasa/message_ix/issues/591#issuecomment-1136024937 and ensure the behaviour remains the same as prior to the merge of #561 

## PR checklist

- [x] Continuous integration checks all ✅
- [x] Add or expand tests; coverage checks both ✅
- ~Add, expand, or update documentation.~ N/A, fix bug to restore intended/documented behaviour
- [x] Update release notes.

### CODE REVIEW

**Comment by khaeru** [comment]
I've restarted one flaky test (failure is the in the R notebook, so unrelated), but otherwise this is complete. So now I'll request a review, with both the failing and passing runs visible.

**Comment by gidden** [comment]
LGTM - elegant solution to reduce code duplication, but does introduce the diamond problem. For now let's just note that here. I highly doubt we will ever run into it given we do not touch these classes often. A pythonic resolution to this for future searchers can be found [here](https://stackoverflow.com/questions/46199975/resolving-diamond-inheritance-within-python-classes) (if it ever becomes a problem).

Happy to merge as is - should we ignore the tutorial failure?

**Review by gidden — APPROVED** [review]

**Comment by khaeru** [comment]
@gidden —thanks for the review, but the merge was a little premature.

Like the comments/description said, I was trying to demonstrate the simple workflow for running the nightly tests on a PR branch. Now we've skipped from step (7) to (9), missing (8), so changes from the "TEMPORARY" commit now appear on `main`.

I'll revert and see if I can fix.

**Comment by khaeru** [comment]
Done via #614.

**Pull request merged**
