### PR TITLE
Embed installation tutorial

### PR DESCRIPTION
**Pull request by LauWien**
This PR embeds the installation tutorial with Anaconda, created by @francescolovat, in the `message_ix` documentation.

cf. #396
 
## How to review

- Read the diff and note that the CI checks all pass.
- Build the documentation and look at the installation page.

## PR checklist

- [x] Continuous integration checks all ✅

### CODE REVIEW

**Comment by LauWien** [comment]
The license/cla check is still "_Waiting for status to be reported_". Unfortunately I'm not quite sure how to change this status.

**Comment by khaeru** [comment]
Thanks for starting this! I think we should probably hold off on merging it until we complete #396. That will result in a video (largely the same) that has the IIASA video intro/outro "stabs" and is on the IIASA YouTube channel. We can then use the ID/URL of that video in this PR.

**Comment by francescolovat** [comment]
Thanks you, @LauWien, I'm afraid I agree with @khaeru here!

**Comment by LauWien** [comment]
> 
> 
> Thank you, @LauWien. I'm afraid I agree with @khaeru here!

Yes, same :)

**Comment by LauWien** [comment]
As this PR is still in the "Draft" stage, we postpone to v3.6.

**Comment by khaeru** [comment]
Closing in favour of #296.

**Comment by LauWien** [comment]
> Closing in favour of #296.

Ah shoot, I forgot 🙈 thank you!

**Pull request closed without merging**
