### PR TITLE
fix py2 westeros

### PR DESCRIPTION
**Pull request by gidden**
# Please confirm that this PR has done the following:

- [ ] Tests Added
- [ ] Documentation Added
- [ ] Description in RELEASE_NOTES.md Added

# Adding to RELEASE_NOTES.md

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

### CODE REVIEW

**Comment by gidden** [comment]
this should fail. if it does, will fix and it will be ready to go.

**Comment by gidden** [comment]
should be fixed after this commit

**Comment by gidden** [comment]
should be good to merge here @danielhuppmann

**Comment by danielhuppmann** [comment]
nice one, thanks @gidden

**Pull request merged**
