### PR TITLE
Enable docs build on ReadTheDocs

### PR DESCRIPTION
**Pull request by khaeru**
In this PR, I've done the following:
- add the necessary pieces for the documentation to be built on ReadTheDocs,
- change the theme to the RTD default theme with the IIASA logo,
- rearrange and simplify duplicated contents, especially in the user/contributor guidelines and FAQ.

I have *temporarily* (i.e. this will **not** be the final URL) enabled the build for this branch (`feature/rtd`), which is available at:

https://message-ix.readthedocs.io/en/feature-rtd/

- [x] Merge #138 and ensure build still works.
- [x] Set up CNAME or redirects from IIASA ENE domains & corresponding RTD config.
- [x] Consider [subprojects](https://docs.readthedocs.io/en/latest/subprojects.html) or other configuration for building docs of MESSAGE-GLOBIOM and ixmp separately → **don't use**
- [x] PR checklist:
  - [x] Tests added (n/a)
  - [x] Documentation added (n/a)
  - [x] Description in RELEASE_NOTES.md added

## Closes

- #155
- #157

## Separately
If we want to enable RTD hosting of older versions (e.g. v1.0.0, v1.1.0), then we will need to:
1. Establish maintenance branches for each version.
2. Add a minimal commit to each branch with changes necessary for the RTD build to work.

### CODE REVIEW

**Comment by khaeru** [comment]
> * [ ]  Set up CNAME from IIASA ENE domains & corresponding RTD config.

This was discussed in today's development meeting, work is on hold pending a decision…

**Comment by khaeru** [comment]
Last thing pending is a decision from @volker-krey on what domain/path these will live under.

**Comment by gidden** [comment]
Looks great @khaeru. What did we decide on migrating tutorials to static doc pages? I know gams was the pain point, but did we come to a conclusion?

**Comment by khaeru** [comment]
@gidden I think the idea was to:
1. Install GAMS as an optional target of message_ix/ixmp.
2. Do this on RTD.
3. Render the tutorials within Sphinx.

I would personally prefer static docs pages, since that seems more in line with what's done by other Pydata packages. Either way, that's a separate can of worms, so we can open a new issue…

**Comment by gidden** [comment]
Agreed. Ok, so we have the scripts to do so on CI, but I would need to read up on how to make `setup.py` do something like this specifically for a target. Perhaps a custom `Install` class?

**Comment by khaeru** [comment]
> Either way, that's a separate can of worms, so we can open a new issue…

Opened #165 for that discussion.

**Comment by khaeru** [comment]
Okay @gidden I think this is ready to merge, if you do.

I will make another PR if needed to implement the final domain/URL scheme.

**Comment by gidden** [comment]
Amazing work, thanks @khaeru!

**Pull request merged**
