### PR TITLE
Update Westeros multinode tutorial for hints

### PR DESCRIPTION
**Pull request by behnam-zakeri**
This PR updates the multinode tutorial for two reasons:
- shortening the code after resolving issue #601 
- adding hints for the in-depth questions

## How to review

Please run Westeros multinode tutorial and make sure the hints provided at the end will work. You can copy-paste those code-based hints at the end of the tutorial and solve the illustrated scenario.

## PR checklist

- [x] Continuous integration checks all ✅
- ~[ ] Add or expand tests; coverage checks both ✅~ Just adding hints to one tutorial
- [X] Add, expand, or update documentation.
- [X] Update release notes.

### CODE REVIEW

**Comment by behnam-zakeri** [comment]
@glatterf42 I added the code-based hints at the end of the tutorial. These can be opened by click. I couldn't'd wrap up the code block using "```", so the code block does not look optimal when the hint is clicked. Maybe you could help me with that.

**Review by glatterf42 — APPROVED** [review]
Looks good to me, thanks :)

The tutorial tests may be failing, but that's unrelated to this PR.

Just to be sure: even after reformatting the code (for which I used markdown and removed the html `<code>` directive), the code can only be copied by editing the cell, not immediately from the rendered output. Is that fine with you?

**Comment by meng25meng** [comment]
你好。我在建立三节点能源系统时，我想表达出节点之间的单向电力传输。把安徽作为电力传输中心向其他两个节点输送电力，但是最后输出的结果，安徽却变成了电力进口方，另外上海节点却变成了电力出口方，是我的哪里没有表达对吗？
A396154BD12238DCCB8AB99B93F902B9
A396154BD12238DCCB8AB99B93F902B9
image

**Comment by behnam-zakeri** [comment]
> Looks good to me, thanks :)
> 
> The tutorial tests may be failing, but that's unrelated to this PR.
> 
> Just to be sure: even after reformatting the code (for which I used markdown and removed the html `<code>` directive), the code can only be copied by editing the cell, not immediately from the rendered output. Is that fine with you?

Thanks @glatterf42 for reviewing this. Yes, the code needs to be copied to a new cell and be run. As far as I know it cannot be hidden in markdown cell and later be run as a code block.

**Comment by glatterf42** [comment]
> 你好。我在建立三节点能源系统时，我想表达出节点之间的单向电力传输。把安徽作为电力传输中心向其他两个节点输送电力，但是最后输出的结果，安徽却变成了电力进口方，另外上海节点却变成了电力出口方，是我的哪里没有表达对吗？ 

@meng25meng, could you please translate this to English? I'm sorry but I don't speak Chinese/Mandarin.

**Comment by meng25meng** [comment]
> > 好。我在建立三个节点能源系统时，我想表达出节点之间的单向电力传输。把安徽作为电力传输中心向其他两个节点管道电力传输，但是最后输出的结果，安徽却变成了电力进口方，其他上海节点却变成了电力出口方，是我的哪里没有表达对吗？
> 
> @meng25meng，你能把这个翻译成英文吗？抱歉，我不会说中文/普通话。

Very sorry，I am establishing a three-node energy system, and I want to express the one-way electricity transmission between the nodes. I want Anhui to act as the electricity transmission center and transmit electricity to the other two nodes. However, in the final output results, Anhui becomes the electricity importing node, while the Shanghai node becomes the electricity exporting node. Where did I go wrong in expressing this?

**Comment by glatterf42** [comment]
@behnam-zakeri if the new name suits you, this PR is good to go :)

**Comment by behnam-zakeri** [comment]
Thanks, @glatterf42, the name sounds more intuitive and representative of the content. I believe this is ready to be merged.

**Pull request merged**
