### PR TITLE
example from @khaeru where clone is broken

### PR DESCRIPTION
**Pull request by gidden**
This is a minimal example from #198 by @khaeru that shows the clone is broken. Output from testing that function is attached.

[output.txt](https://github.com/iiasa/message_ix/files/3232345/output.txt)

### CODE REVIEW

**Comment by gidden** [comment]
cc @khaeru @danielhuppmann @zikolach 

This PR is currently a branch on our org repo. Others investigating this issue, please feel free to take it from here.

**Comment by gidden** [comment]
And a short snippet from the failure:

```
    def test_clone(tmpdir):
        # Two local platforms
        mp1 = ixmp.Platform(tmpdir / 'mp1', dbtype='HSQLDB')
        mp2 = ixmp.Platform(tmpdir / 'mp2', dbtype='HSQLDB')
    
        # A minimal scenario
        scen1 = Scenario(mp1, model='model', scenario='scenario', version='new')
        scen1.add_spatial_sets({'country': 'Austria'})
        scen1.add_set('technology', 'bar')
        scen1.add_horizon({'year': [2010, 2020]})
        # ADDED: Store data
        mp1.add_unit('$')
        data = pd.DataFrame(dict(node_loc='Austria', technology='bar',
                                 year_vtg=2010, value=1.2, unit='$'), index=[0])
        scen1.add_par('inv_cost', data)
        pdt.assert_frame_equal(scen1.par('inv_cost').astype({'value': float}),
                               data)
        scen1.commit('add minimal sets for testing')
    
        assert len(mp1.scenario_list(default=False)) == 1
    
        # Clone
        scen2 = scen1.clone(platform=mp2)
    
        # Return type of ixmp.Scenario.clone is message_ix.Scenario
        assert isinstance(scen2, Scenario)
    
        # ADDED: Data can be retrieved from clone
        print('Cloned data:')
        print(scen2.par('inv_cost'))
        print('Original data:')
        print(data)
>       pdt.assert_frame_equal(scen2.par('inv_cost'), data)
E       AssertionError: DataFrame are different
E       
E       DataFrame shape mismatch
E       [left]:  (0, 5)
E       [right]: (1, 5)
```

**Comment by danielhuppmann** [comment]
currently working on cleaning as part of `message_ix` release 1.2, it works as expected here: https://github.com/danielhuppmann/ixmp/blob/a3ba46a358ed61da3f66b83ad24c7f2b910620ce/tests/test_integration.py#L111

**Comment by gidden** [comment]
Perhaps in that test suite it is worth also cloning a scenario *with* a
solution across platforms to confirm that solutions also come across?

**Comment by gidden** [comment]
my understanding is that this is now fixed on the master branches, closing

**Pull request closed without merging**
