### PR TITLE
Include Python version 3.10 and remove 3.6 in CI

### LINKED ISSUE #532: Include Python version 3.10 and remove 3.6 in CI
On the 4th of October Python 3.10 got released which lead to the failing of parts of our CI workflows. 
Among others the following issues and errors appeared: 

**nightly.yaml** / **lint.yaml**
_Install Python packages and dependencies_ / _Check typing with mypy_
```
Building wheel for numba (setup.py): finished with status 'error'
...
Building wheel for llvmlite (setup.py): finished with status 'error'
..."etc."
ModuleNotFoundError: No module named 'numpy'
..."etc."
Running setup.py install for llvmlite: finished with status 'error'
..."etc."
```

This might be due to the delayed adjustments of the packages we depend on related to the Python version 3.10.

A hot-fix got implemented in https://github.com/iiasa/message_ix/pull/529  where the usage of 3.10 in our CI was repressed. 
However this interferes with keeping our CI up to date.

The following ToDos arise:

- [ ] implement needed adjustments on our part to satisfy lint.yaml and nightly.yaml
- [ ] implement the version 3.10 into the pytest.yaml matrix [here ](https://github.com/iiasa/message_ix/blob/main/.github/workflows/pytest.yaml)
- [ ] remove support for 3.6, analogue to https://github.com/iiasa/ixmp/issues/434

### PR DESCRIPTION
**Pull request by LauWien**
This PR includes Python version 3.10 and removes Python version 3.6 in CI. 
Closes #532 

## How to review

- Read the diff and note that the CI checks all pass.

## PR checklist

- [ ] Continuous integration checks all ✅
- [ ] Add, expand, or update documentation.
- [ ] Update release notes.

### CODE REVIEW

**Comment by khaeru** [comment]
Sorry for not advertising more loudly, but I made these changes incidentally in the branch for #557. I was expecting to merge that quickly, but it is stalled on #559.

**Comment by LauWien** [comment]
> Sorry for not advertising more loudly, but I made these changes incidentally in the branch for #557. I was expecting to merge that quickly, but it is stalled on #559.

Oh shoot, sorry I didn't check deeply!
I started https://github.com/iiasa/message_ix/pull/565 to fix #559, by first forcing to use the new pandas release 1.4.1, since the _test_add_year.py_ was running through successful locally with that version. The tests were also successful on GHA, but then I saw with that new errors occur, see [here](https://github.com/iiasa/message_ix/actions/runs/1880963897/attempts/1). So I thought, I should maybe first check the offending lines here https://github.com/iiasa/message_ix/pull/565/commits/f7c13744848228339787a97db1b0892a820616da which led to the same failing tests [here](https://github.com/iiasa/message_ix/runs/5290499094?check_suite_focus=true) like described in https://github.com/iiasa/message_ix/pull/565, so I reverted https://github.com/iiasa/message_ix/pull/565/commits/6c3ef88b05b00b182bc709247ced04a32c5191fa and started this new PR here to first tackle the failing tests on Python version 3.6 and after the failing tests in ubuntu-latest.
So right now I think we don't need to adapt the offending lines since with the latest pandas version the test _test_add_year.py_, which failed previously, were successful, but remove Python version 3.6 and tackle the failing ubuntu-latest tests. What do you think?

Regarding the failing ubuntu-test e.g. the following error:
```
File /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/message_ix/models.py:359, in GAMSModel.run(self, scenario)
E               340 """Execute the model.
E               341 
E               342 GAMSModel creates a file named ``cplex.opt`` in the model directory
E              (...)
E               348    each process may produced unexpected results.
E               349 """
E               350 # If two runs are kicked off simulatenously with the same
E               351 # self.model_dir, then they will try to write the same optfile, and may
E               352 # write different contents.
E              (...)
E               357 
E               358 # Write CPLEX options into an options file
E           --> 359 optfile = self.model_dir / "cplex.opt"
E               360 lines = ("{} = {}".format(*kv) for kv in self.cplex_opts.items())
E               361 optfile.write_text("\n".join(lines))
E           
E           TypeError: unsupported operand type(s) for /: 'str' and 'str'
E           TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

It seems like the whitespace in line 359 `optfile = self.model_dir / "cplex.opt"` is ignored, which leads to a string division.

**Comment by khaeru** [comment]
This TypeError is the very thing that #557 is meant to address.

**Comment by LauWien** [comment]
> This TypeError is the very thing that #557 is meant to address.

:woman_facepalming: sorry.. 
So then I guess I can close https://github.com/iiasa/message_ix/pull/566 and https://github.com/iiasa/message_ix/pull/565, since with `pandas==1.4.1` the _test_add_year.py_ is successful.

**Pull request closed without merging**
