### PR TITLE
Improve reporting (phase 2)

### PR DESCRIPTION
**Pull request by khaeru**
This will partially implement the second phase of the [reporting update](https://github.com/iiasa/message_ix/wiki/Reporting#phase-2).

The goal is to have a basic subset of requirements met in message_ix 1.2 / ixmp 0.2 in an experimental state, and then proceed with the remainder for the next release.

Supersedes #176, which was from a branch in a fork; all can commit to this branch.

**See also:**

- iiasa/ixmp#150 for corresponding changes in `ixmp`.
- iiasa/message_data#41 for corresponding changes in the MESSAGE global model.
- #149 master issue.

**Progress**
Address requirements from wiki:
- [x] B1. Provide equal support for any type of model that can be built in MESSAGEix, i.e. do not restrict based on specific features of any one model:
  - ~e.g. Clara's "hospital" model, i.e. where the 'node' set does not map to countries or geographical regions.~ deferred; we lack a concrete `message_ix.testing` function that sets up this model.
  - [x] the Westeros and ~Austria~ tutorial models.
  - ~Single-country models, e.g. South Africa, Israel, others built using Behnam's tools.~ deferred, ditto.
  - ~Models with 'extra' features/detail added: MESSAGE-Access, MESSAGE-Transport.~ deferred, ditto.
  - [x] the MESSAGE global model(s).
    - Basic reporting runs in a cleaned-up version of MESSAGEix-GLOBIOM; see iiasa/message_data#41.
- [x] B2. Provide zero-config reporting, i.e. reporting that is automatically configured by introspection of the model structure. Including: calculate all outputs of commodities at all levels.
- [x] B3. Support user-defined operations:
  - ~B3i. …on exogenous sub-sets of model sets.~ deferred, requires a specific example, perhaps drawn from iiasa/message_data.
  - ~B3ii. …that exclude quantities from aggregation operations.~ deferred, ditto.
  - [x] B3iii. …that compute the same quantity in different ways.
  - ~B3iv. Cumulative quantities with defined start and end periods.~ deferred, ditto.
- [x] B4. Support user-defined reports.
  - [x] B4i. …defined programmatically.
  - ~B4ii. …loaded from a configuration file.~ deferred, ditto.
- ~B5. Provide (either automatically or per user input) operations related to model features including:~ deferred, ditto.
  - ~B5i. …sub-annual time steps.~
  - ~B5ii. …bi-directional commodity flows.~
  - ~B5iii. …user-defined relations. (Probably not automatic; user will need to define reporting.)~

PR checklist
- [x] Tests added (ongoing)
- [x] ~Tests merged with Phase 1 tests.~ N/A, cancelled.
- [x] Documentation added — **preview [here](https://message.iiasa.ac.at/en/feature-reporting2/reporting.html).**
- [x] Description in RELEASE_NOTES.md added.

Miscellaneous
- [x] Choose target release: ~1.3 or 2.0?~ 1.2
- [x] @gidden w/ assist from @khaeru: add…
  - additional computations for common MESSAGE quantities, e.g. of `'tom = fom + vom`.
  - add keys for the 'standard' form of these quantities with keys like `'std:tom'`.
  - add a key like `'all:message'` that collects these standard quantities.
- [x] @khaeru update docs to parity with ixmp `master`.

### CODE REVIEW

**Comment by gidden** [comment]
@khaeru ok with you if I force push a rebased branch?

**Comment by gidden** [comment]
we need to remember to remove CI branch assignment after iiasa/ixmp#150 is merged

**Comment by gidden** [comment]
looks like doc making is failing: `ImportError: cannot import name 'check_year' from 'ixmp.utils' (/home/travis/build/iiasa/message_ix/doc/src/ixmp/ixmp/utils.py)`

**Comment by gidden** [comment]
Hmm, this actually did get clobbered with the add_years PR. Is this something you could look into briefly @khaeru ?

**Comment by khaeru** [comment]
> Hmm, this actually did get clobbered with the add_years PR. Is this something you could look into briefly @khaeru ?

Done.

> looks like doc making is failing: `ImportError: cannot import name 'check_year' from 'ixmp.utils' (/home/travis/build/iiasa/message_ix/doc/src/ixmp/ixmp/utils.py)`

The name `check_year` was introduced in iiasa/ixmp#142 and so is on the ixmp `master` branch but not ixmp `feature/reporting2`. When the latter is merged this should go away.

**Comment by khaeru** [comment]
Tests are passing here now that iiasa/ixmp#150 is merged.

Added two remaining tasks to the PR description.

**Comment by gidden** [comment]
Ok, I will take a stab at task one above, likely during travel to Korea tomorrow..

**Comment by khaeru** [comment]
All greens! We will merge this tomorrow morning unless @danielhuppmann comes up with any critical last-minute TODOs.

**Comment by danielhuppmann** [comment]
thanks @khaeru and @gidden for this great new reporting module!

**Pull request merged**
