### PR TITLE
Update Westeros RES diagram source file

### PR DESCRIPTION
**Pull request by OFR-IIASA**
The current base_res.png file cannot be edited or updated, therefore a pptx has been added allow the updating and renewable of the RES when required.

## How to review
Look at the pptx in westros tutorial folder as well as the westeros_baseline and _fossil_resource tutorials to ensure the figures render correctly.

## PR checklist

- ~Add or expand tests.~ N/A
- ~Add, expand, or update documentation.~ N/A
- [x] Update release notes.

### CODE REVIEW

**Review by behnam-zakeri — CHANGES_REQUESTED** [review]
Thanks @OFR-IIASA for developing this resource. Two points from me:
1. Are you representing wind like coal as resource in resource_volume? If not, and what I recommend is that, to represent wind as a renewable resource via "renewable_potential". This can be a separate column in the chart, i.e., "renewable resources" and "depleting resources".
2. The color used for wind as commodity is the same as color for electricity. It is better to give a different color, like green.

**Comment by khaeru** [comment]
Postponed to 3.3 so the review comments can be addressed. The branch also needs a rebase.

**Review by behnam-zakeri — APPROVED** [review]

**Comment by khaeru** [comment]
@behnam-zakeri @OFR-IIASA —I see this is approved, but the PR still has "WIP" in the label, and there are two check-boxes that haven't been completed or marked ~...~ N/A. Can you please update the PR title and description to accurately reflect the state?

**Comment by OFR-IIASA** [comment]
@khaeru the changes have been made as requested and the merge conflicts resolved.

**Comment by khaeru** [comment]
Will rebase to address (a) the merge conflict in the release notes due to #460 and (b) [commit message format](https://docs.messageix.org/en/stable/contributing.html#code-style).

**Pull request merged**
