### PR TITLE
Fixdl

### LINKED ISSUE #64: Tutorials Download Latest Version (not installed version)
@Jihoon (in #62) and @ClaraLuisa (in #63) separately ran into this issue. The basic problem is that `messageix-dl` will download the *current* version of tutorials, which are designed to be used with the *current* version of the master branch. However, when installing from anaconda (or otherwise), they should download the version of the tutorials aligned with the version installed. 

This will likely require also #29

### PR DESCRIPTION
**Pull request by gidden**
Fixes #64 

# Please confirm that this PR has done the following:

- [x] Tests Added
- [x] Documentation Added
- [x] Description in RELEASE_NOTES.md Added

# Adding to RELEASE_NOTES.md

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

### CODE REVIEW

**Comment by gidden** [comment]
@ClaraLuisa this should fix the issue you saw in #63

**Comment by ClaraLuisa** [comment]
Thanks @gidden I'll try again as soon this is merged.

**Comment by gidden** [comment]
@jihoon, also relevant for you

**Comment by ClaraLuisa** [comment]
Hey @gidden are you going to merge this or should i somehow just copy/paste your changes into "*my*" message?

**Comment by gidden** [comment]
Hi Clara - hoping someone would review it first =)

**Pull request merged**
