### PR TITLE
Update nightly.py with a better error message

### LINKED ISSUE #297: better error message for tests failure with wrong installation approach
At the moment, if you install `message_ix` with `python setup.py install` or `pip install .` (*without* `-e`/`--editable`), you get the following error when running tests:

```
_____________________________________________________________________________________ ERROR collecting tests/test_nightly.py ______________________________________________________________________________________
tests/test_nightly.py:28: in <module>
    ids, args = zip(*iter_scenarios())
../../../../.local/lib/python3.7/site-packages/message_ix-1.2.0-py3.7.egg/message_ix/testing/nightly.py:77: in iter_scenarios
    with open(HERE.parents[2] / 'tests' / 'data' / 'scenarios.yaml', 'r') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/gidden/.local/lib/python3.7/site-packages/message_ix-1.2.0-py3.7.egg/tests/data/scenarios.yaml'
```

Perhaps it is worth catching this and adding an explicit message stating to install with `pip install . -e`?

### PR DESCRIPTION
**Pull request by francescolovat**
This PR closes #297.

Following #297, this 1-commit piece of code provides a better error message suggesting to have installed **message_ix** using `--editable` to explain to the user that the error in `nightly.py` when using **pytest** is for that reason.

### CODE REVIEW

**Comment by gidden** [comment]
The installation is only "incorrect" only in the sense that the tests cannot be run. I guess the other option would be to move this check into `conftest.py` and have it run at module level?

**Comment by francescolovat** [comment]
hi both, I'm not an experienced developer so I'll try to move this check whenever you both find it more suitable. I'll be pending for your final decision

**Comment by francescolovat** [comment]
@khaeru thanks for your comment. 

I edited it as you suggests. I'm afraid `Codecov` will fail again. Would that decrease in coverage be an issue?

**Comment by khaeru** [comment]
> what is the policy with codecov here?

> I'm afraid `Codecov` will fail again. Would that decrease in coverage be an issue?

I thought I fixed this previously by adding this line to our codecov.yaml file:
https://github.com/iiasa/message_ix/blob/544fc3ce4a9eb1f5510a35de09320f9e20077e08/ci/codecov.yml#L11-L13

Not sure why it isn't ignoring that file.

**Comment by khaeru** [comment]
Note that the Travis Linux check is failing because of some dependency snafu in Anaconda:

```
==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_reporting.py ___________________
tests/test_reporting.py:12: in <module>
    import pyam
../../../miniconda/envs/testing/lib/python3.8/site-packages/pyam/__init__.py:3: in <module>
    from pyam.core import *
../../../miniconda/envs/testing/lib/python3.8/site-packages/pyam/core.py:17: in <module>
    from pyam import plotting
../../../miniconda/envs/testing/lib/python3.8/site-packages/pyam/plotting.py:5: in <module>
    import matplotlib.pyplot as plt
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/pyplot.py:2349: in <module>
    switch_backend(rcParams["backend"])
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/__init__.py:833: in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/pyplot.py:204: in switch_backend
    switch_backend(candidate)
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/pyplot.py:221: in switch_backend
    backend_mod = importlib.import_module(backend_name)
../../../miniconda/envs/testing/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/backends/backend_qt5agg.py:11: in <module>
    from .backend_qt5 import (
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/backends/backend_qt5.py:15: in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/backends/qt_editor/figureoptions.py:13: in <module>
    from matplotlib.backends.qt_compat import QtGui
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/backends/qt_compat.py:153: in <module>
    _setup()
../../../miniconda/envs/testing/lib/python3.8/site-packages/matplotlib/backends/qt_compat.py:69: in _setup_pyqt5
    from PyQt5 import QtCore, QtGui, QtWidgets
E   RuntimeError: the sip module implements API v12.0 to v12.4 but the PyQt5.QtCore module requires API v12.5
```
The installed versions are:
```
    pyqt-5.9.2                 |   py38h05f1152_4         4.5 MB
    qt-5.9.7                   |       h5867ecd_1        68.5 MB
…
    sip-4.19.8                 |   py38he6710b0_0         277 KB
```

The Travis macOS check continues to pass with
```
    pyqt-5.9.2                 |   py36h655552a_2         3.6 MB
    qt-5.9.7                   |       h468cd18_1        62.0 MB
…
    sip-4.19.8                 |   py36h0a44026_0         238 KB
```

@gidden I am not sure if this is the direct cause of the issue, but any clue why conda chooses to install these `py38…` builds of packages when the Python/Miniconda installed is Python 3.7?

In any case, I think this is not an obstacle, so I will merge this PR and we can address that elsewhere.

**Pull request merged**
