### PR TITLE
initial draft of first standard message reporting

### PR DESCRIPTION
**Pull request by gidden**
Hi @khaeru and @danielhuppmann. Here is my crack at the second bullet point on #206. I think it gets us most of the way there structurally, but please feel free to further edit the internals as desired. There are a number of `TODO`s I left open, as I didn't have internet access on the plane to Korea and now will be busy with the meeting. You're more than welcome to address them (or not) as needed to get #206 in for the release.

There are a few key points I ran across:

1. I didn't have a chance to generalize the collapse functions using `eval`. I think this can go in as-is with an issue stating it should be cleaned up later if you prefer. It is a bit ugly at the moment..
2. When making a collection of tasks like `rep.add('super-task', ['set', 'of', 'subtasks'])`, I think it would be useful to either explicitly support or have helper functions to chain results back into a single returned list/container. At the moment it returns a list of return types, which gets cumbersome when they themselves are lists, etc. I tried playing around with `itertools.chain()` and `np.ravel()` which are my usual go-tos, but neither worked off the shelf for me... again, no internet.
3. **most important** there is currently a test failure in `test_reporter_from_westeros`. I explain in comments what the observed behavior is, which is related to unit registration. This definitely needs to be fixed before #206 can go into the release.

### CODE REVIEW

**Comment by gidden** [comment]
Also to note, I made the PR so you can cleanly see the diff. I can't promise to have time to make further changes on my end, given the time difference and meeting. But I'll do my best to respond to feedback as needed - you may have to tarry on without me =)

**Comment by khaeru** [comment]
@gidden thanks for handling the bulk of this while in the :airplane:! Will carry on from here.

**Comment by gidden** [comment]
And sorry for the stickler, I really need to go back to my `.emacsrc` on the new laptop..

**Comment by khaeru** [comment]
> **most important** there is currently a test failure in `test_reporter_from_westeros`. I explain in comments what the observed behavior is, which is related to unit registration. This definitely needs to be fixed before #206 can go into the release.

Good catch, thanks. I quickly did iiasa/ixmp#155 to resolve this issue. Restarting tests…

**Comment by khaeru** [comment]
> 1. I didn't have a chance to generalize the collapse functions using `eval`. I think this can go in as-is with an issue stating it should be cleaned up later if you prefer. It is a bit ugly at the moment..

This is now done.

**Comment by khaeru** [comment]
> 2. When making a collection of tasks like `rep.add('super-task', ['set', 'of', 'subtasks'])`, I think it would be useful to either explicitly support or have helper functions to chain results back into a single returned list/container. At the moment it returns a list of return types, which gets cumbersome when they themselves are lists, etc. I tried playing around with `itertools.chain()` and `np.ravel()` which are my usual go-tos, but neither worked off the shelf for me... again, no internet.

Since the test expresses that you'd eventually want to `concat()` these IamDataFrames, I just added a one-line computation that does that and made each `message:<foo>` report and `message:default` return a single object.

Maybe that will be problematic (too big?) when it comes to the global model, but seems tidy for now.

**Comment by khaeru** [comment]
Stickler here is complaining about things that no longer exist, so I'm just going to merge this.

**Pull request merged**
