### PR TITLE
A tutorial for representing sub-annual time steps in a MESSAGEix model

### PR DESCRIPTION
**Pull request by behnam2015**
# Please confirm that this PR has done the following:

- [ ] Tests Added
- [ ] Documentation Added
- [x] Description in RELEASE_NOTES.md Added

# Adding to RELEASE_NOTES.md

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

### CODE REVIEW

**Comment by gidden** [comment]
Hi @behnam2015 this looks great! I really like the question/discussion section as well =). Can you please coordinate with @OFR-IIASA as discussed in the meeting and open a single PR with all of the new tutorials?

My goal will also be to get them explicitly on our website at the same time (similarly to how we do it in pyam: https://pyam-iamc.readthedocs.io/en/latest/tutorials.html)

**Comment by behnam2015** [comment]
Thank you @gidden for the feedback! Isn't it better to have a separate PR for each tutorial to track the comments and commits more easily?

**Comment by gidden** [comment]
Normally you want one PR per "feature" or "bugfix". However, given that there are ~8ish new tutorials, I think it would be easier on the reviewer to look through them all at once. It will also give us the opportunity to update our docs/CI, hence my preference.

Probably the best way to get started is simply pushing this branch to `upstream` so that both you and @OFR-IIASA can commit to it and it can easily be reviewed. At the same time I can do the doc refactor. Sound good?

**Comment by behnam2015** [comment]
Thanks @gidden for the points! These tutorials are independent of each other and developed by different contributors. I'm afraid piling them all in one PR may not ease the process of review and approval. Also, the approval of all tutorials then has to wait until the review and approval of each and every of them. If the goal is harmonization between tutorials, I suggest we prepare a guide for that.

**Pull request closed without merging**
