### PR TITLE
Implement feature to enforce commodity balance equality

### PR DESCRIPTION
**Pull request by gidden**
moving adrivinca/message_ix#1 to here for better communication

### CODE REVIEW

**Comment by gidden** [comment]
ok @danielhuppmann I have updated our scenario tests to have multiple test cases. For example, we can now test objective functions and carbon prices. There is a `README` in the directory tests/ci which explains how to run things locally (fetching the database, make the test file, etc.). Would you mind adding an integration test for the price commodity there?

**Comment by gidden** [comment]
will rebase this after #173 is merged

**Comment by gidden** [comment]
moved merge base to master, since #171 was closed

**Comment by danielhuppmann** [comment]
rebased following merge of #173

**Comment by danielhuppmann** [comment]
changing target for clean integration into all changes related to release 1.2

**Pull request merged**
