### PR TITLE
Westeros tutorials release 2 0

### PR DESCRIPTION
**Pull request by jkikstra**
Improving the Westeros tutorials for MESSAGE_ix 2.0 release.

The changes in this PR adress all the points raised in issue #245 ([link to specific post](https://github.com/iiasa/message_ix/issues/245#issuecomment-564639143)).

### CODE REVIEW

**Comment by francescolovat** [comment]
thanks @jkikstra for your improvements! I slightly edited some small formatting things.

Btw, now I am getting an error with the `Plots` function from the `tools` python package. @khaeru I wonder why... I run these tutorials some weeks ago and I was not getting this error (I did **NOT** update my `Python 3.7.3` since then). So, basically I cannot see the plots anymore...

image

image

**Comment by francescolovat** [comment]
Now I've talked with @behman-zakeri in the bus and I think I can solve it

**Comment by jkikstra** [comment]
Okay @francescolovat your changes look good to me. Please let me know if you can run this and then if successful we can merge this in.

**Comment by francescolovat** [comment]
Hi @jkikstra,

the comments you've added in the last to commits seem great to me! good level of detail! thank you again 😃 

I solved the problem with the plotting, it has taken me way too much time: The issue I was having when plotting was due to 16 recent commits in `ixmp` I did not merge to my `master` branch and I did non re-installed from source both `message_ix` and `ixmp` packages. 

In other words, in my opinion **we are ready to merge** this PR.

**Pull request merged**
