### PR TITLE
Set duration_period in add_horizon() 

### LINKED ISSUE #282: add_horizon() should also set 'duration_period'
`Scenario.add_horizon()` is provided as a shorthand for setting the 'year' and 'cat_year' sets.

To help the user even more, if they give e.g.:
```python
scen.add_horizon([1995, 2000, 2005, 2010, 2020])
```
…the helper method should infer that the durations of the latter periods are 5, 5, 5, and 10 years respectively.

NB. the duration of the first period is not fully determined by the arguments, e.g. the period '1995' in the example above could be 5, 10, or 1000 years long. This will require some intuitive behaviour, clearly documented.

Other changes that could be made at the same time:
- Replace the single `data` argument with keyword arguments.
- Clarify and test whether it should be possible to call add_horizon more than once. If so perhaps warn or return a value if the user adds overlapping sets of years; if not, raise an exception.

Noticed while working on #281.

### PR DESCRIPTION
**Pull request by francescolovat**
This PR closes #282.

This PR edits the `add_horizon` method for `Scenario` class found in `/message_ix/core.py`

Change of `data` argument to `**kwargs`, and added automatic generation of *duration_period* parameter. Added description in the docstring of `add_horizon`.

Still, from #282 the following bullet needs to be addressed:

> - Clarify and test whether it should be possible to call add_horizon more than once. If so perhaps warn or return a value if the user adds overlapping sets of years; if not, raise an exception.

Please help, @khaeru I don't know why the changes in the `core.py` file are not reflected in the jupyter notebook files for the tutorials (I was testing my changes in the Westeros tutorial file but nothing was changing when I was editing or even commenting some methods in `core.py`).

**PR checklist:**

- [x] Tests added.
- [x] Documentation added.
- [x] Release notes updated.

### CODE REVIEW

**Comment by khaeru** [comment]
> Please help, @khaeru I don't know why the changes in the `core.py` file are not reflected in the jupyter notebook files for the tutorials (I was testing my changes in the Westeros tutorial file but nothing was changing when I was editing or even commenting some methods in `core.py`).

I guess you were not restarting the kernel or Jupyter—right? Searching for "Jupyter module reload" brings [this](https://support.enthought.com/hc/en-us/articles/204469240-Jupyter-IPython-After-editing-a-module-changes-are-not-effective-without-kernel-restart) and [this](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html) as first results.

**Comment by khaeru** [comment]
Postponing to after v3.0.

**Comment by khaeru** [comment]
Per discussion in Slack, I'll jump in here to help complete this.

**Comment by khaeru** [comment]
Thanks @francescolovat!

**Comment by francescolovat** [comment]
Thank you @khaeru for improving and merging this work! I see that just a little of my code survided to your exhaustive revision  :sweat_smile:

**Pull request merged**
