### PR TITLE
added model='MESSAGE' to solve command to run

### PR DESCRIPTION
**Pull request by ClaraLuisa**

### CODE REVIEW

**Comment by gidden** [comment]
Hi @ClaraLuisa, thanks for making a PR. I do not think this is needed, however, as the [`message_ix.Scenario.solve()`](https://github.com/iiasa/message_ix/blob/master/message_ix/core.py#L120) automatically adds this for you. Do you see some different behavior?

**Comment by ClaraLuisa** [comment]
HEy @gidden , thanks for the fast reply. Without the model statement it runs into an error message asking for the model as an input. Do I need to update messageix?

**Comment by gidden** [comment]
yes, this uses the latest version

**Comment by gidden** [comment]
closing in favor of #65

**Pull request closed without merging**
