### PR TITLE
Update add_year for turning off some warnings and adding bound extension option

### PR DESCRIPTION
**Pull request by behnam-zakeri**
This PR modifies the tool `add_year` for:
turning off some warning in python and adding an option to extend the bound

**PR checklist:**

- [X] Tests added
- [x] Documentation added.
- [X] Release notes updated.

### CODE REVIEW

**Comment by OFR-IIASA** [comment]
@khaeru the PR failed on two tests. The Travis build showed some issues with language options. How can this be corrected?

**Comment by khaeru** [comment]
> @khaeru the PR failed on two tests. The Travis build showed some issues with language options. How can this be corrected?

```
___________________________ test_bound_emission_year ___________________________
…
>   to_jlist2(filter(lambda e: e in values, elements)))
E   TypeError: argument of type 'int' is not iterable
```
These failures, and related failures on other message_ix PRs, are related to iiasa/ixmp#225.

If you trace the code, `elements` is ultimately from `filters`. That PR adds the lines:
https://github.com/iiasa/ixmp/blob/657aa5181f9ce61676c407e45cdcec5a16f19e9c/ixmp/backend/jdbc.py#L496-L499
…so that the bare `int` value used in that test (`... filters={'year': 2020}`) is converted to a list of str (`... filters={'year': ['2020']}`).

The tests here should be restarted after that PR is completed and merged.

**Comment by behnam-zakeri** [comment]
Thanks @OFR-IIASA for testing and checking the code. I removed those extra lines.

**Comment by OFR-IIASA** [comment]
> hese failures, and related failures on other message_ix PRs, are related to [iiasa/ixmp#225](https://github.com/iiasa/ixmp/pull/225).

In reference to the above failure, @Behnam, [iiasa/ixmp#225](https://github.com/iiasa/ixmp/pull/225) was now merged into the master. So could you please update your branch to the current master so that we can see if the problems are resolved and the tests pass? Thanks, Oliver

**Comment by khaeru** [comment]
The latest failures (e.g. [Travis job #1299.1](https://travis-ci.org/iiasa/message_ix/jobs/620441830#L1730)) are upstream, in IPython or similar:
```
NbConvertApp] Converting notebook /home/travis/build/iiasa/message_ix/tests/../tutorial/Austrian_energy_system/austria.ipynb to notebook

Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testing/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/travis/miniconda/envs/testing/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/miniconda/envs/testing/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/travis/miniconda/envs/testing/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/travis/miniconda/envs/testing/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/home/travis/miniconda/envs/testing/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/travis/miniconda/envs/testing/lib/python3.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/travis/miniconda/envs/testing/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 20, in <module>
    from prompt_toolkit.formatted_text import PygmentsTokens
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
```

This seems to be a (new) dependency issue unrelated to this PR. I can investigate when I have time, but in the interim help is welcome.

**Comment by OFR-IIASA** [comment]
@behnam-zakeri can you please update this branch to the master. @khaeru once this branch is updated to the master, if the only issue is the above dependency failure, I would suggest merging this if thats ok by you?

**Comment by khaeru** [comment]
> I can investigate when I have time, but in the interim help is welcome.

Since no one was able to do this in the last 8 days, I addressed in #283.
88f7f12 merges that change into this branch, so let's see if the tests pass.

**Comment by khaeru** [comment]
> let's see if the tests pass.

FYI @OFR-IIASA @behnam-zakeri, they do.

The PR checklist is not complete: the last item is “Documentation updated.” Does the documentation clearly and fully describe what the code does, after these changes?

I'll review once (a) the checklist is complete and (b) the CI checks pass.

**Comment by behnam-zakeri** [comment]
Thanks a lot @khaeru for resolving the issues for passing the tests. Related to documentation, this PR has no new changes that needs to be documented. It corrects a part of the code to generate the expected outcome. Perhaps I add a test for this part that was corrected?

**Comment by khaeru** [comment]
> Perhaps I add a test for this part that was corrected?

That would be welcome, but let's do that in a new PR. Merging this now on Oliver's review in order to get ready for 2.0.

**Pull request merged**
