### PR TITLE
Fix 2-platform cloning & associated tests

### LINKED ISSUE #174: platform cloning broken in message_ix
At the moment, we support cloning models into different platforms in `ixmp`. This is currently broken in `message_ix` for two reasons:

- the same issue originally found in `ixmp` - the java object was not being passed the correct new platform
- `message_ix.Scenario` defines its own clone function, thus circumventing the fix provided in `ixmp`

This brings up a larger question of polymorphism (PM) and depedency between the two `Scenario` classes. I would suggest when fixing this issue that we also review the current state of PM and try to minimize custom code on the `message_ix` side where possible, depending instead of common PM best practices.

### PR DESCRIPTION
**Pull request by khaeru**
This PR…
- closes #174 by deleting `message_ix.Scenario.clone()`, letting `ixmp.Scenario.clone()` do the work.
- fixes tests broken by [ixmp#130](https://github.com/iiasa/ixmp/pull/130).
- adds tests for cloning of MESSAGEix scenarios.

**PR checklist:**
- [x] Tests added
- [x] Documentation added
- [x] Description in RELEASE_NOTES.md added

### CODE REVIEW

**Comment by gidden** [comment]
g2g here for review @khaeru ?

**Comment by gidden** [comment]
Ah, some test failures, I'll wait to review until passage

**Comment by khaeru** [comment]
The tests will not pass until [ixmp#132](https://github.com/iiasa/ixmp/pull/132) is merged.

**Comment by gidden** [comment]
Ok, merged ixmp/#132 and restarted CI

**Comment by gidden** [comment]
Looks great, thank you @khaeru !!

**Pull request merged**
