### PR TITLE
WIP: Improve reporting (phase 2)

### PR DESCRIPTION
**Pull request by khaeru**
This will implement the second phase of the [reporting update](https://github.com/iiasa/message_ix/wiki/Reporting#phase-2).

**See also:**

- iiasa/ixmp#144 for corresponding changes in `ixmp`
- iiasa/message_data#41 for corresponding changes in the MESSAGE global model.
- #142 for phase 1
- #149 master issue for both phases.

**Progress**
Address requirements from wiki:
- [ ] B1. Provide equal support for any type of model that can be built in MESSAGEix, i.e. do not restrict based on specific features of any one model:
  - [ ] e.g. Clara's "hospital" model, i.e. where the 'node' set does not map to countries or geographical regions.
  - [ ] the Westeros and Austria tutorial models.
  - [ ] Single-country models, e.g. South Africa, Israel, others built using Behnam's tools.
  - [ ] Models with 'extra' features/detail added: MESSAGE-Access, MESSAGE-Transport.
  - [ ] the MESSAGE global model(s).
- [x] B2. Provide zero-config reporting, i.e. reporting that is automatically configured by introspection of the model structure. Including: calculate all outputs of commodities at all levels.
- [ ] B3. Support user-defined operations:
  - [ ] B3i. …on exogenous sub-sets of model sets.
  - [ ] B3ii. …that exclude quantities from aggregation operations.
  - [x] B3iii. …that compute the same quantity in different ways.
  - [ ] B3iv. Cumulative quantities with defined start and end periods.
- [ ] B4. Support user-defined reports.
  - [x] B4i. …defined programmatically.
  - [ ] B4ii. …loaded from a configuration file.
- [ ] B5. Provide (either automatically or per user input) operations related to model features including:
  - [ ] B5i. …sub-annual time steps.
  - [ ] B5ii. …bi-directional commodity flows.
  - [ ] B5iii. …user-defined relations. (Probably not automatic; user will need to define reporting.)

PR checklist
- [x] Tests added (ongoing)
- [ ] Tests merged with Phase 1 tests.
- [x] Documentation added — **preview [here](https://message-ix-khaeru.readthedocs.io/en/reporting2/reporting.html).**
- [x] Description in RELEASE_NOTES.md added.

Miscellaneous
- [x] Choose target release: ~1.3 or 2.0?~ 1.2

### CODE REVIEW

**Comment by gidden** [comment]
not sure, but this one may need to be rebased too @khaeru ? I'm just looking through the code/docs at the moment, not yet running anything.

**Comment by khaeru** [comment]
Echoing [this comment](https://github.com/iiasa/ixmp/pull/126#issuecomment-498149008), and per discussion today with @volker-krey and @gidden, the plan is now:

1. Merge this into `master` more or less as-is,
2. Release it with [1.2](https://github.com/iiasa/message_ix/milestone/2) in the next week or two as clearly-marked ‘experimental’ code,
3. Refine with smaller PRs based on dogfooding with 2019 YSSPers and their supervisors, and
4. Promote from ‘experimental’ status in a major release ([2.0](https://github.com/iiasa/message_ix/milestone/3), probably late 2019).

**Comment by khaeru** [comment]
There's now a link to the preview docs build in the PR description.

**Comment by khaeru** [comment]
It seems flake8, used by Stickler, won't let me ``# noqa: E241`` to keep definitions in a readable alignment. See https://gitlab.com/pycqa/flake8/issues/63 :sob:

**Comment by khaeru** [comment]
Superseded by #206.

**Pull request closed without merging**
