### PR TITLE
Record message_ix version in scenario data & GDX

### LINKED ISSUE #739: Split tutorial tests to separate CI job
The "pytest" CI workflow takes up to 20 minutes (Windows) to run, which makes it less useful for its intended purpose of quick feedback on PRs. Most of the 20 longest-duration tests are tutorial tests.

One way to address this:
- Add a second job named "tutorials" within the pytest.yaml workflow file.
- In this job, run only the tests of the tutorials. This might be done for only one Python version.
- In the "pytest" job, omit the test of the tutorials.

Other benefits: we could upload Codecov reports for only the "pytest" workflow. This would help us see if there is any code that is currently tested *only* through its use in a tutorial, and add more direct (faster, simpler) tests.

### LINKED ISSUE #747: Record message_ix version in scenario data & GDX I/O
The GDX file generated by ixmp.JDBCBackend has a parameter named `MESSAGE_ix_version` with values like {"major": 2, "minor": 0}. The original intent of this was to aid with debugging when inspecting/comparing GDX files.

This has not been updated for recent MESSAGE versions, for multiple reasons:
- It is a "stack level violation", in other words in the wrong place: ixmp (or its backends) should be agnostic to whether they are being used by message_ix or not; similarly, logic relevant to message_ix should be actually _in_ message_ix.
- The team lacks a Java developer capable of updating the code and the JAR file in ixmp.

Raised by @volker-krey in the [2023-10-19 MESSAGEix meeting](https://iiasahub.sharepoint.com/sites/eceprog/_layouts/15/Doc.aspx?sourcedoc={2a354107-351e-43ab-8824-542f007aa2ff}&action=edit&wd=target%282023.one%7C010d73b1-6bc1-492d-b32a-c6143fe2b0f2%2F10-19%20Monthly%7Cba547214-3f13-463d-8a64-2a2472bb19da%2F%29&wdorigin=703).

## Fix

- We can use the code underlying `show_versions()` to generate a string with more informative version information (like " 3.7.1.dev55+g2e0a9c49"), and store this in a parameter.
- This can be updated in `message_ix.Scenario.solve()`.
- The name should be something other than "MESSAGE_ix_version" (perhaps just "version"?) in order to avoid a collision with the (fixed) behaviour of the Java code.

### PR DESCRIPTION
**Pull request by khaeru**
Closes #747.

Housekeeping:
- Close #739. This appears to bring the job time down to:
  - 4:40–10 minutes for the tests —so the first indication of success/failure comes in under 5 minutes, which is more fit for purpose.
  - 8–12 minutes for the tutorials.
- [x] Update older tests. The above change caused some of these to begin to fail, which makes me suspect they rely on state leaking from the tutorial tests or are otherwise fragile. The updates should ensure the tests are complete.
  - `test_equation_NEW_CAPACITY_CONSTRAINT.py::test_new_capacity_up`: fix typo in the file name. Clone the subject scenario to a unique URL, so that GDX I/O files do not collide even if the two test cases are run in parallel.
  - `test_integration.py`, `test_macro.py`: similarly clone to unique URLs.
  - Expand some flaky marks from #731 that were previously scoped to macOS only, to now apply to all platforms:
    - `test_feature_bound_activity_shares.py::test_add_bound_activity_up_all_modes`
    - `test_feature_price_emission.py::test_custom_type_variable_periodlength`
    - `test_integration::test_multi_db_run`.
- Advertise and test Python 3.12 support.
- Update copyright year to 2024.

## How to review

Read the diff and note that the CI checks all pass.

## PR checklist

- [x] Merge required changes upstream: iiasa/ixmp#502.
- [x] Continuous integration checks all ✅
  
- [x] Add or expand tests; coverage checks both ✅
- [x] Add, expand, or update documentation.
- [x] Update release notes.

### CODE REVIEW

**Comment by khaeru** [comment]
@glatterf42 FYI, looking at the recent commits on the branch, I am finding that for some apparently flaky tests, it helps to `.clone(scenario=request.node.name)` first.

I think this is because we are using pytest-xdist: where this results in 2+ tests with identical model name and scenario names being run in parallel, then strange effects can occur; for instance, one test reads and sees the result from the GDX file of the other test. (This occurs because message_ix tries to heed users' desire to keep GDX I/O files all in the same directory, rather than separate, temporary directories per-run as the base ixmp GAMSModel class does.)

[`request.node.name`](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.FixtureRequest.node) is from the Pytest `request` fixture, and gives a string that is unique to each test—including individual cases of parametrized tests. It's the easiest way to get such a unique label.

We could later (no urgency) try this approach to address other apparently flaky tests.

**Comment by glatterf42** [comment]
Very useful catch, would be great to remove some flaky markers :)

**Comment by glatterf42** [comment]
Just rebasing onto current main.

**Review by glatterf42 — APPROVED** [review]
LGTM, thanks :)

**Comment by glatterf42** [comment]
Rebased after dependabot update to main: are we just seeing flakiness in these tests?

**Comment by glatterf42** [comment]
Looks like flakiness; are we merging regardless and clean up/apply markers later if needed?

**Comment by khaeru** [comment]
> are we merging regardless and clean up/apply markers later if needed?

I would say the latter.

I have adapted several tests in this PR to ensure they use unique model/scenario names; this means there is no chance that another scenario being run in another pytest-xdist worker thread will try to access the same scenario in the database or in a GDX file. However, this is different from doing a full sweep through the test suite or adapting fixtures to be sure that *no* test has this fragility. We can do that in a subsequent PR.

**Pull request merged**
