### PR TITLE
Share constraints for level/commodity

### PR DESCRIPTION
**Pull request by gidden**
# Please confirm that this PR has done the following:

- [x] Tests Added
- [x] Documentation Added
- [x] Description in RELEASE_NOTES.md Added

# Adding to RELEASE_NOTES.md

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

### CODE REVIEW

**Comment by gidden** [comment]
closed #79 so we can have easier discussions on PRs.

**Comment by danielhuppmann** [comment]
lgtm, thanks @gidden and @OFR-IIASA 

added the required changes in the MESSAGE-scheme of the ixmp Java source code, see https://github.com/iiasa/ixmp/issues/70

**Comment by danielhuppmann** [comment]
holding off on merging until the MESSAGE-scheme in `ixmp.jar` is updated

**Comment by gidden** [comment]
close in favor of #91

**Pull request closed without merging**
