### PR TITLE
Generic share constraint bounds

### PR DESCRIPTION
**Pull request by gidden**
Here's the start of a test @danielhuppmann 

# Please confirm that this PR has done the following:

- [ ] Tests Added
- [ ] Documentation Added
- [ ] Description in RELEASE_NOTES.md Added

# Adding to RELEASE_NOTES.md

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

### CODE REVIEW

**Comment by gidden** [comment]
note this can also use `mode='all'` for the transport technology

**Comment by danielhuppmann** [comment]
can we split up the tests into multiple files and call them `test_feature_{}.py`, like `test_feature_addon.py`? These tests are getting quite lenghty... Also, running the add-on test first is not ideal - should first test core features, then the MESSAGE-specific features...

**Comment by gidden** [comment]
Yes, as you wish. In principle, the order of tests should not matter (they should be independent of order). Please feel free to implement as you see fit.

**Comment by gidden** [comment]
rebased on most recent hackathon prs. should be good to go at your convenience @danielhuppmann

**Comment by gidden** [comment]
@danielhuppmann, I took a shot at implementing the first upper bound constraint. I have tests which pass and confirm it works in principle. I'm sure it's ugly, but I think it covers the broad strokes of our discussion today.

@OFR-IIASA, this should be ready for testing if you want to go for it. `mode == 'all'` is supported.

**Comment by gidden** [comment]
Great PR @danielhuppmann, should we be good to go after docs are included?

**Comment by gidden** [comment]
and after stickler is appeased? =P

**Comment by gidden** [comment]
want me to make this PR based on an upstream branch so you can commit directly?

**Pull request merged**
