### PR TITLE
Adjust standard set of reported products

### PR DESCRIPTION
**Pull request by gidden**
Adds more reporting capability per (private repo): https://github.com/iiasa/message_data/wiki/Reporting

**PR checklist:**

- [x] Tests added.
- [x] Documentation added. (N/A)
- [x] Release notes updated (N/A)

### CODE REVIEW

**Comment by gidden** [comment]
@khaeru should now pass. we should probably still check in the `ixmp.Reporter` or maybe `message_ix.Reporter` that the `scenario.has_solution()` before doing anything. Otherwise I guess this is good to go and we can continue progress on the wiki?

**Comment by khaeru** [comment]
@gidden what behaviour should depend on the presence of a solution?

**Comment by gidden** [comment]
@khaeru, there is an inherent implication that any "reporting" is done on a model *with* a solution. To keep things simple, I will add this here briefly and we can decide later if we want to push it up into `ixmp`.

**Comment by gidden** [comment]
OK @khaeru this should be good to go now. @OFR-IIASA time to move on to our next topic! All, I have updated the Wiki. Perhaps we can sit down briefly on Friday to discuss next steps and how to get others involved.

**Comment by khaeru** [comment]
Thanks @gidden :+1:

**Pull request merged**
