### PR TITLE
Update Westeros tutorial: flexible generation

### PR DESCRIPTION
**Pull request by OFR-IIASA**
This PR updates the tutorial on adding flexible generation constraints.

This is the second of three tutorials on various features surrounding the renewables.

## How to review

Run tutorial
Read through tutorials and see if the explanantions are understandable 

## PR checklist

~ - [ ] Tests added. Tutorial added~
~ - [ ] Documentation added. already included ~
- [x] Release notes updated.

### CODE REVIEW

**Comment by khaeru** [comment]
Postpone to v3.3, as indicated by @OFR-IIASA on 2021-01-13.

**Review by behnam-zakeri — COMMENTED** [review]
Thanks @OFR-IIASA for this useful tutorial and improving the format. I suggested some text edits through [this PR ](https://github.com/OFR-IIASA/message_ix/pull/7).
Otherwise, this is ready to merge.

**Comment by behnam-zakeri** [comment]
Thanks @OFR-IIASA for the improvements. @khaeru this is ready to be merged.

**Review by khaeru — APPROVED** [review]
Thanks both for the work. Code looks good. Will squash and merge because of the [commit message format](https://chris.beams.io/posts/git-commit/#seven-rules).

**Pull request merged**
